/**
 * Lucide Icon Registry
 * Centralized icon mapping for dynamic icon selection
 *
 * Used by: app-sidebar (menu icons), and any component needing dynamic icons
 */

import type { LucideIcon } from 'lucide-react';
import {
    // Core UI
    ListChecks,
    Activity,
    FileText,
    Github,
    Key,
    LayoutDashboard,
    Settings,
    Shield,
    UserCheck,
    Users,
    // Navigation & Layout
    Menu,
    Home,
    Archive,
    Folder,
    FolderOpen,
    Grid3X3,
    Layers,
    Navigation,
    Sidebar as SidebarIcon,
    // User & Profile
    User,
    UserPlus,
    UserMinus,
    UserX,
    UserCog,
    User2,
    UsersRound,
    Contact,
    // Business & Finance
    Building,
    Building2,
    Briefcase,
    Calculator,
    CreditCard,
    DollarSign,
    Wallet,
    TrendingUp,
    TrendingDown,
    BarChart,
    BarChart2,
    BarChart3,
    BarChart4,
    LineChart,
    PieChart,
    // Communication
    Mail,
    MailOpen,
    MessageCircle,
    MessageSquare,
    Send,
    Phone,
    PhoneCall,
    Video,
    Mic,
    MicOff,
    // Media & Files
    Image,
    Camera,
    Film,
    Music,
    Upload,
    Download,
    File,
    Files,
    FilePlus,
    FileX,
    FileEdit,
    // Tools & Utilities
    Search,
    Filter,
    Calendar,
    Clock,
    Timer,
    Bookmark,
    Tag,
    Tags,
    Bell,
    BellOff,
    // Actions
    Plus,
    Minus,
    X,
    Check,
    CheckCircle,
    XCircle,
    AlertCircle,
    AlertTriangle,
    Info,
    HelpCircle,
    // Navigation Arrows
    ArrowUp,
    ArrowDown,
    ArrowLeft,
    ArrowRight,
    ChevronUp,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    ChevronsUp,
    ChevronsDown,
    ChevronsLeft,
    ChevronsRight,
    // Edit & Content
    Edit,
    Edit2,
    Edit3,
    Pen,
    PenTool,
    Type,
    Bold,
    Italic,
    Underline,
    // System & Settings
    Cog,
    Sliders,
    Power,
    RefreshCcw,
    RotateCcw,
    RotateCw,
    Lock,
    Unlock,
    Eye,
    EyeOff,
    // Shopping & E-commerce
    ShoppingCart,
    ShoppingBag,
    Store,
    Package,
    Package2,
    Truck,
    // Technology
    Monitor,
    Smartphone,
    Tablet,
    Laptop,
    Server,
    Database,
    HardDrive,
    Wifi,
    WifiOff,
    // Social & Sharing
    Share,
    Share2,
    Heart,
    HeartHandshake,
    Star,
    ThumbsUp,
    ThumbsDown,
    // Location & Map
    Map,
    MapPin,
    Navigation2,
    Compass,
    Globe,
    // Weather
    Sun,
    Moon,
    Cloud,
    CloudRain,
    Zap,
    // Health & Medical
    Stethoscope,
    Pill,
    Cross,
    Thermometer,
    // Gaming & Entertainment
    Gamepad,
    Gamepad2,
    Trophy,
    Award,
    Medal,
    // Transportation
    Car,
    Plane,
    Train,
    Bike,
    Bus,
    // Food & Drink
    Coffee,
    Cookie,
    Pizza,
    Wine,
    // Nature
    Flower,
    Trees,
    Leaf,
    // Miscellaneous
    Gift,
    Lightbulb,
    Flame,
    Target,
    Crosshair,
    Anchor,
    Flag,
    FlagTriangleRight,
    Link,
    Link2,
    ExternalLink,
    Paperclip,
    Copy,
    Clipboard,
    ClipboardCopy,
    Save,
    Trash,
    Trash2,
    MoreHorizontal,
    MoreVertical,
    Maximize,
    Maximize2,
    Minimize,
    Minimize2,
    ZoomIn,
    ZoomOut,
    Expand,
    Shrink,
    Square,
    Circle,
    Triangle,
    Hexagon,
    Octagon,
    Pentagon,
    Diamond,
    Box,
    Code,
    Code2,
    Terminal,
    Command,
    Hash,
    AtSign,
    Percent,
    DollarSign as Dollar,
    Repeat,
    Repeat1,
    Repeat2,
    Shuffle,
    SkipBack,
    SkipForward,
    FastForward,
    Rewind,
    Play,
    Pause,
    CircleStop,
    PlayCircle,
    PauseCircle,
    StopCircle,
    Radio,
    Disc,
    Disc2,
    Disc3,
    Headphones,
    Speaker,
    Volume,
    Volume1,
    Volume2,
    VolumeOff,
    VolumeX,
    PlusCircle,
    MinusCircle,
    // Movement & Direction
    Move,
    MoveHorizontal,
    MoveVertical,
    MousePointer,
    MousePointer2,
    Hand,
    // Organization
    Kanban,
    GitBranch,
    GitCommit,
    GitMerge,
    Workflow,
    // Print & Export
    Printer,
    FileOutput,
    FileInput,
    Import,
    // Quality & Rating
    BadgeCheck,
    Badge,
    Verified,
    // Accessibility
    Accessibility,
} from 'lucide-react';

/**
 * Icon Registry Map
 * Maps string names to Lucide icon components
 */
export const iconRegistry: Record<string, LucideIcon> = {
    // Core UI
    ListChecks,
    Activity,
    FileText,
    Github,
    Key,
    LayoutDashboard,
    Settings,
    Shield,
    UserCheck,
    Users,
    // Navigation & Layout
    Menu,
    Home,
    Archive,
    Folder,
    FolderOpen,
    Grid3X3,
    Layers,
    Navigation,
    SidebarIcon,
    // User & Profile
    User,
    UserPlus,
    UserMinus,
    UserX,
    UserCog,
    User2,
    UsersRound,
    Contact,
    // Business & Finance
    Building,
    Building2,
    Briefcase,
    Calculator,
    CreditCard,
    DollarSign,
    Wallet,
    TrendingUp,
    TrendingDown,
    BarChart,
    BarChart2,
    BarChart3,
    BarChart4,
    LineChart,
    PieChart,
    // Communication
    Mail,
    MailOpen,
    MessageCircle,
    MessageSquare,
    Send,
    Phone,
    PhoneCall,
    Video,
    Mic,
    MicOff,
    // Media & Files
    Image,
    Camera,
    Film,
    Music,
    Upload,
    Download,
    File,
    Files,
    FilePlus,
    FileX,
    FileEdit,
    // Tools & Utilities
    Search,
    Filter,
    Calendar,
    Clock,
    Timer,
    Bookmark,
    Tag,
    Tags,
    Bell,
    BellOff,
    // Actions
    Plus,
    Minus,
    X,
    Check,
    CheckCircle,
    XCircle,
    AlertCircle,
    AlertTriangle,
    Info,
    HelpCircle,
    // Navigation Arrows
    ArrowUp,
    ArrowDown,
    ArrowLeft,
    ArrowRight,
    ChevronUp,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    ChevronsUp,
    ChevronsDown,
    ChevronsLeft,
    ChevronsRight,
    // Edit & Content
    Edit,
    Edit2,
    Edit3,
    Pen,
    PenTool,
    Type,
    Bold,
    Italic,
    Underline,
    // System & Settings
    Cog,
    Sliders,
    Power,
    RefreshCcw,
    RotateCcw,
    RotateCw,
    Lock,
    Unlock,
    Eye,
    EyeOff,
    // Shopping & E-commerce
    ShoppingCart,
    ShoppingBag,
    Store,
    Package,
    Package2,
    Truck,
    // Technology
    Monitor,
    Smartphone,
    Tablet,
    Laptop,
    Server,
    Database,
    HardDrive,
    Wifi,
    WifiOff,
    // Social & Sharing
    Share,
    Share2,
    Heart,
    HeartHandshake,
    Star,
    ThumbsUp,
    ThumbsDown,
    // Location & Map
    Map,
    MapPin,
    Navigation2,
    Compass,
    Globe,
    // Weather
    Sun,
    Moon,
    Cloud,
    CloudRain,
    Zap,
    // Health & Medical
    Stethoscope,
    Pill,
    Cross,
    Thermometer,
    // Gaming & Entertainment
    Gamepad,
    Gamepad2,
    Trophy,
    Award,
    Medal,
    // Transportation
    Car,
    Plane,
    Train,
    Bike,
    Bus,
    // Food & Drink
    Coffee,
    Cookie,
    Pizza,
    Wine,
    // Nature
    Flower,
    Trees,
    Leaf,
    // Miscellaneous
    Gift,
    Lightbulb,
    Flame,
    Target,
    Crosshair,
    Anchor,
    Flag,
    FlagTriangleRight,
    Link,
    Link2,
    ExternalLink,
    Paperclip,
    Copy,
    Clipboard,
    ClipboardCopy,
    Save,
    Trash,
    Trash2,
    MoreHorizontal,
    MoreVertical,
    Maximize,
    Maximize2,
    Minimize,
    Minimize2,
    ZoomIn,
    ZoomOut,
    Expand,
    Shrink,
    Square,
    Circle,
    Triangle,
    Hexagon,
    Octagon,
    Pentagon,
    Diamond,
    Box,
    Code,
    Code2,
    Terminal,
    Command,
    Hash,
    AtSign,
    Percent,
    Dollar,
    Repeat,
    Repeat1,
    Repeat2,
    Shuffle,
    SkipBack,
    SkipForward,
    FastForward,
    Rewind,
    Play,
    Pause,
    CircleStop,
    PlayCircle,
    PauseCircle,
    StopCircle,
    Radio,
    Disc,
    Disc2,
    Disc3,
    Headphones,
    Speaker,
    Volume,
    Volume1,
    Volume2,
    VolumeOff,
    VolumeX,
    PlusCircle,
    MinusCircle,
    // Movement & Direction
    Move,
    MoveHorizontal,
    MoveVertical,
    MousePointer,
    MousePointer2,
    Hand,
    // Organization
    Kanban,
    GitBranch,
    GitCommit,
    GitMerge,
    Workflow,
    // Print & Export
    Printer,
    FileOutput,
    FileInput,
    Import,
    // Quality & Rating
    BadgeCheck,
    Badge,
    Verified,
    // Accessibility
    Accessibility,
};

/**
 * Get Lucide icon component by name
 * Returns undefined if icon not found
 *
 * @param iconName - String name of the icon (e.g., 'Home', 'Users', 'Settings')
 * @returns LucideIcon component or undefined
 *
 * @example
 * const HomeIcon = getIcon('Home');
 * if (HomeIcon) return <HomeIcon className="w-4 h-4" />;
 */
export function getIcon(iconName: string): LucideIcon | undefined {
    return iconRegistry[iconName];
}

/**
 * Check if icon exists in registry
 *
 * @param iconName - String name of the icon
 * @returns boolean
 */
export function hasIcon(iconName: string): boolean {
    return iconName in iconRegistry;
}
